---

- name: iterate for each node and remove label
  include: remove-node-labels.yml
  vars:
    node: "{{ item }}"
    labels: "{{ hostvars[item]['m7s_k8s_labels'] }}"
  when: hostvars[item]['m7s_k8s_labels'] is defined
  with_items: "{{ groups['all'] }}"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: true

- name: iterate for each node and add label
  include: add-node-labels.yml
  vars:
    node: "{{ item }}"
    labels: "{{ hostvars[item]['m7s_k8s_labels'] }}"
  when: hostvars[item]['m7s_k8s_labels'] is defined
  with_items: "{{ groups['all'] }}"
  delegate_to: "{{ groups['kube-master'][0] }}"
  run_once: true
