---

- set_fact:
      labels_dict:  "{{ (labels_dict|default({})) | combine({ item.item.key: None }) }}"
  when:
    - item.resources is defined
    - item.resources | length > 0
  with_items:
    - "{{ node.results }}"

- debug:
    msg: "{{ labels_dict }}"

- name: in a node vars not included
  k8s:
    state: present
    merge_type: strategic-merge
    kind: Node
    name: "{{ inventory_hostname }}"
    definition:
      metadata:
        labels:
          "{{ labels_dict }}"
  when: labels_dict is defined
